const events=[
  {date:'14 days ago',type:'refactor',title:'Split payment flow into authorization + capture',copy:'Method extraction in checkout/authorize.ts changed alongside ledger/entry.ts and events/payment.ts.',tag:'STRUCTURAL'},
  {date:'29 days ago',type:'bug',title:'Retry failed webhooks without double-charging',copy:'Three rollback commits cluster around the webhook boundary. This is the highest scar-tissue signal in the repository.',tag:'SCAR TISSUE'},
  {date:'2 months ago',type:'feature',title:'Introduce idempotency keys',copy:'A new dependency path formed between api/payment-route.ts and storage/idempotency.ts.',tag:'FEATURE'},
  {date:'5 months ago',type:'refactor',title:'Extract currency normalization service',copy:'A class split reduced local complexity but increased co-change coupling with the ledger package.',tag:'STRUCTURAL'},
  {date:'9 months ago',type:'bug',title:'Fix race condition in settlement worker',copy:'The worker has accumulated 18 bug-fix commits since its first introduction in 2021.',tag:'SCAR TISSUE'}
];
const hotspots=[
  ['checkout/authorize.ts','0.91','38','18','high'],['events/webhook-retry.ts','0.86','31','12','high'],['ledger/entry.ts','0.78','24','7','med'],['workers/settlement.ts','0.73','19','5','med'],['api/payment-route.ts','0.66','16','3','low'],['storage/idempotency.ts','0.58','11','1','low']
];
const files=[['checkout/authorize.ts','0.91','2.1 yrs','high'],['ledger/entry.ts','0.78','4.8 yrs','med'],['events/webhook-retry.ts','0.86','1.4 yrs','high'],['workers/settlement.ts','0.73','3.2 yrs','med'],['api/payment-route.ts','0.66','2.8 yrs','low'],['storage/idempotency.ts','0.58','0.6 yrs','low'],['domain/currency.ts','0.32','4.1 yrs','low'],['events/payment.ts','0.82','2.0 yrs','med'],['config/feature-flags.ts','0.21','5.2 yrs','low']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showView(view){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===`view-${view}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:'The codebase remembers.',timeline:'Every refactor leaves a layer.',graph:'Coupling is the hidden skeleton.', 'scar-tissue':'Where the code keeps getting hurt.',files:'Biological age by file.'};$('#view-title').textContent=titles[view]||titles.overview;window.scrollTo({top:0,behavior:'smooth'});}
function renderTimeline(filter='all'){const data=filter==='all'?events:events.filter(e=>e.type===filter);$('#timeline-detail').innerHTML=data.map(e=>`<div class="event"><div class="event-date">${e.date}</div><div class="event-marker ${e.type}"></div><div><h3>${e.title}</h3><p>${e.copy}</p></div><span class="event-tag">${e.tag}</span></div>`).join('');}
function renderHotspots(){ $('#hotspot-table').innerHTML='<div class="hotspot-row head"><span>REGION</span><span>COUPLING</span><span>CHURN / 90D</span><span>BUG FIXES</span><span>RISK</span></div>'+hotspots.map(h=>`<div class="hotspot-row"><span class="file-name">${h[0]}</span><span><strong>${h[1]}</strong></span><span>${h[2]}</span><span>${h[3]}</span><span class="risk ${h[4]}">${h[4].toUpperCase()}</span></div>`).join('');}
function renderFiles(query=''){const data=files.filter(f=>f[0].includes(query.toLowerCase()));$('#file-grid').innerHTML=data.map(f=>`<article class="file-card"><h3>${f[0]}</h3><div class="age">${f[2]}</div><p>Structural stability score <strong>${f[1]}</strong></p><div class="bar"><span style="width:${parseFloat(f[1])*100}%"></span></div><p><span class="risk ${f[3]}">${f[3]} risk</span></p></article>`).join('');}
function drawGraph(graph){const svg=$('#mutation-graph');const palette=['#e87560','#84c4a4','#b3a5d9','#e4b35e','#84c4a4','#e4b35e'];const positions=[[210,210,42],[415,115,34],[555,250,35],[190,90,28],[440,345,30],[640,100,27]];const names=graph?.nodes?.slice(0,6)||['checkout','ledger','webhooks','api','settlement','idempotency'];const nodes=names.map((name,i)=>[name,positions[i][0],positions[i][1],positions[i][2],palette[i]]);const index=new Map(nodes.map((n,i)=>[n[0],i]));const edges=graph?.edges?.map(e=>[index.get(e.source),index.get(e.target),Math.min(8,e.weight)])?.filter(e=>e[0]!==undefined&&e[1]!==undefined)||[[0,1,5],[0,2,3],[0,3,2],[1,4,4],[1,2,2],[2,4,3],[2,5,1],[3,0,2]];svg.innerHTML=edges.map(([a,b,w])=>{const A=nodes[a],B=nodes[b];return `<line x1="${A[1]}" y1="${A[2]}" x2="${B[1]}" y2="${B[2]}" stroke="${w>=4?'#e87560':'#c5d9cb'}" stroke-width="${w}" opacity=".72"/>`}).join('')+nodes.map((n,i)=>`<g class="graph-node" data-node="${i}"><circle cx="${n[1]}" cy="${n[2]}" r="${n[3]}" fill="${n[4]}" opacity=".96"/><text x="${n[1]}" y="${n[2]+4}" text-anchor="middle" fill="#fff" font-size="${n[3]>35?12:10}" font-family="DM Mono">${n[0].split('/').pop().slice(0,12)}</text></g>`).join('');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
const modal=$('#repo-modal');const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>$('#repo-input').focus(),50)};const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
function relativeDate(date){const days=Math.max(0,Math.round((Date.now()-new Date(`${date}T00:00:00Z`))/86400000));return days<30?`${days} days ago`:days<365?`${Math.round(days/30)} months ago`:`${(days/365).toFixed(1)} years ago`}
function applyAnalysis(data){events.splice(0,events.length,...data.timeline);hotspots.splice(0,hotspots.length,...data.hotspots);files.splice(0,files.length,...data.files);$('#repo-name').textContent=data.repo;$('#age-years').innerHTML=`${data.summary.ageYears.toFixed(1)} <span>years</span>`;$('#metric-hotspots').textContent=`${data.summary.hotspots} hotspots`;
$('#metric-hotspots-sub').textContent=`${data.summary.files} files scanned`;$('#metric-coupling').textContent=data.summary.coupling.toFixed(2);$('#metric-latest').textContent=data.latest?relativeDate(data.latest.date):'No commits';$('#metric-latest-sub').textContent=data.latest?data.latest.subject:'—';$('#metric-ast').textContent=data.summary.astEvents.toLocaleString();$('#metric-ast-sub').textContent=`across ${data.summary.files} files`;renderTimeline();renderHotspots();renderFiles();drawGraph(data.graph);toast(`Analysis complete — ${data.summary.totalCommits.toLocaleString()} commits indexed.`)}
let currentRepo='';
async function analyzeRepository(repo){currentRepo=repo;toast('Indexing Git history…');try{if(location.protocol==='file:')throw new Error('Start start.bat, then open http://localhost:4173');const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repo})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Analysis failed');applyAnalysis(payload)}catch(error){toast(error.message==='Failed to fetch'?'Backend unavailable — run start.bat first.':error.message);}}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$$('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewJump)));$('#timeline-filter').addEventListener('change',e=>renderTimeline(e.target.value));$('#file-search').addEventListener('input',e=>renderFiles(e.target.value));$('#run-analysis').addEventListener('click',()=>{if(!currentRepo)return toast('Load a repository first.');analyzeRepository(currentRepo)});$('#load-repo').addEventListener('click',openModal);$('#close-modal').addEventListener('click',closeModal);$('#cancel-repo').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});$('#confirm-repo').addEventListener('click',()=>{const value=$('#repo-input').value.trim();if(!value){toast('Add a local path or Git URL first.');return}closeModal();analyzeRepository(value)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});renderTimeline();renderHotspots();renderFiles();drawGraph();if(location.protocol==='file:')setTimeout(()=>toast('Run start.bat, then open http://localhost:4173'),250);
